### PR TITLE
Fix tests on API 3.6

### LINKED ISSUE #15: Test failures on vapoursynth-api-36 on VapourSynth R57
VapourSynth R57 fails `vapoursynth-api-36` tests across all OSes. Windows says it's `STATUS_STACK_BUFFER_OVERRUN`: https://github.com/YaLTeR/vapoursynth-rs/runs/4850789438?check_suite_focus=true#step:6:7231

VapourSynth R53 works fine, so the error started happening somewhere after R53.

### PR DESCRIPTION
**Pull request by quietvoid**
The old `setMessageHandler` API seemingly does nothing when passed a null function pointer.
Also updated example to fix deprecation warnings from clap.

Fixes #15

### CODE REVIEW

**Comment by YaLTeR** [comment]
Ugh, looks like some gha Ubuntu mirrors are acting up again... In the mean time could you please fix the formatting issue?

**Comment by quietvoid** [comment]
I've fixed the python tests as well, will add it in another commit.

**Comment by quietvoid** [comment]
Hm well at least it compiles. There seems to be a bit of difference with R53.
I can't even get the passthrough filter test to pass locally with R58.

I guess there are paths that are breaking without API4 support, like variable format clips.
We're currently returning no format, while it's expecting at least `cfUndefined` now.

**Comment by quietvoid** [comment]
Ignore previous post, it does seem like a plugin returning a variable format clip is impossible now.
So I don't know what to do about the passthrough/invert tests for now.

I've fixed `get_frame` to return an error if the frame number is invalid for the clip.
I was very tempted to switch the error type, but it might break things.

File: vapoursynth/src/node/mod.rs [hunk 1]
```diff
@@ -104,22 +105,40 @@ impl<'core> Node<'core> {
...
+                    CString::new("Requested frame number beyond the last one").unwrap();
+                return Err(GetFrameError::new(Cow::Owned(err_cstring)));
+            }
+        }
+
+        #[cfg(feature = "gte-vapoursynth-api-32")]
+        if n >= vi.num_frames {
+            let err_cstring = CString::new("Requested frame number beyond the last one").unwrap();
+            return Err(GetFrameError::new(Cow::Owned(err_cstring)));
+        }
```
Comment (YaLTeR) [inline vapoursynth/src/node/mod.rs:131]: Is this really needed here? As far as I can tell, Vapoursynth does its own check: https://github.com/vapoursynth/vapoursynth/blob/d06204cab2e4fa0e352449f88d6f30c2d4ce54c9/src/cython/vapoursynth.pyx#L2075-L2085

Comment (quietvoid) [reply vapoursynth/src/node/mod.rs:131]: It is. That check only applies to Python.

I'm pretty sure we're calling https://github.com/vapoursynth/vapoursynth/blob/d06204cab2e4fa0e352449f88d6f30c2d4ce54c9/src/core/vsapi.cpp#L122
Which is always returning a pointer, though I presume it should be null and it isn't for some reason.

The `ArgumentTestFilter` would fail without the check.

Comment (quietvoid) [reply vapoursynth/src/node/mod.rs:131]: Actually, only `getFrameAsync` verifies that the requested index is valid.
So in a way `getFrame` is a lower level API.

Comment (YaLTeR) [reply vapoursynth/src/node/mod.rs:131]: Hm, so it returns a non-null pointer and no error for invalid frame indices? Let's leave the check then, but could you report that to VapourSynth? They've been quite responsive to my past bug reports over the development of these bindings.

Comment (quietvoid) [reply vapoursynth/src/node/mod.rs:131]: I did create https://github.com/vapoursynth/vapoursynth/issues/850

File: vapoursynth/src/node/mod.rs [hunk 2]
```diff
@@ -104,22 +105,40 @@ impl<'core> Node<'core> {
     }
 
     /// Generates a frame directly.
+    /// Returns an error if the requested frame number is beyond the `VideoInfo` num_frames.
```
Comment (YaLTeR) [inline vapoursynth/src/node/mod.rs]:
```suggestion
```
I think this goes without additional saying.

File: vapoursynth/src/node/mod.rs (hunk 1 above)
Comment (YaLTeR) [reply vapoursynth/src/node/mod.rs:131]: So does this mean that with variable frame count there's no way to `get_frame()` safely atm?

Comment (quietvoid) [reply vapoursynth/src/node/mod.rs:131]: > So does this mean that with variable frame count there's no way to `get_frame()` safely atm?

I don't really know how the old API worked but `num_frames` is always positive and non-zero now.

File: vapoursynth/src/node/mod.rs (hunk 2 above)
Comment (quietvoid) [reply vapoursynth/src/node/mod.rs]: Thanks! Fixed.

**Comment by YaLTeR** [comment]
Thanks a lot for figuring this out!
